### PR TITLE
Added BIG DIVE 8 course

### PR DESCRIPTION
**Pull request by pendolare**
Please, I would like to include our Data Science ML / DL Summer School in your great list.
BIG DIVE 8 - www.bigdive.eu
Thanks in advance

### CODE REVIEW

**Comment by pendolare** [comment]
Hi,
Did you have the chance to check my pull-request. Please let me know if I made any mistakes in the procedure to suggest a new summer school.
Thanks in advance.

**Comment by sshkhr** [comment]
@pendolare Thanks a lot for sharing. The Big Dive 8 seems more like a bootcamp than a summer school. Could you please point me to a list of speakers etc. I couldn't find them on the webpage immediately

**Comment by pendolare** [comment]
Thanks for the reply. Actually we are probably in the middle between a bootcamp and a more "traditional" summer school in the sense that there are multiple arguments during the 4-week course.
List of speakers is still "in progress". Some names here: Alan Perotti and Andrè Panisson (ISI Foundation), Stefania Delprete (TOP-IX), Fabio Franchino (TODO), Mario Cartia (AgileLab), Francesco Tarasconi (CELI), Alessandro Molina (Axant), Maurizio Napolitano (FBK),....

**Comment by sshkhr** [comment]
I'm sorry but this is not a summer school in strict terms hence I'm not including this

**Pull request closed without merging**
