### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by RoyMachineLearning**
Added a new summer school, organized virtually in Canada.

### CODE REVIEW

**Comment by sshkhr** [comment]
Thank you for the contribution! Could you please make sure that the School is placed in its correct position chronologically (in reverse order by date of the school)?

**Review by sshkhr — CHANGES_REQUESTED** [review]
Please move the school to its correct chronological position

**Comment by RoyMachineLearning** [comment]
Made the necessary changes

**Comment by alysia2019** [comment]
您好，我已收到您的邮件，会尽快回复您的消息。Good luck,Arden

**Comment by gmberton** [comment]
The school exists in the "Recurring Summer Schools" section

**Pull request closed without merging**
